const $ = s => document.querySelector(s);
const main = $('#mainContent');
const state = {
  page:'home', level:'全部学段', group:'全部主题', query:'', dictPage:1,
  selected:WORDS[0], practiceIndex:0, spellingIndex:0, spellingResult:null,
  speechMessage:'先听一遍发音，再点击「开始跟读」大声说出来吧！',
  onlineWord:null
};
const names={home:'学习首页',primary:'小学英语',dictionary:'单词字典',speaking:'口语跟读',dictation:'单词默写',saved:'我的单词本'};
const key='word-sprout-progress-v1';
let progress;
try { progress=JSON.parse(localStorage.getItem(key))||{}; } catch { progress={}; }
progress.saved ||= [];
progress.learned ||= [];
progress.spelled ||= [];
progress.spoken ||= [];
progress.curriculumLearned ||= [];
progress.days ||= [];
const save=()=>{try{localStorage.setItem(key,JSON.stringify(progress));}catch{}};
const today=()=>new Date().toLocaleDateString('en-CA');
const markDay=()=>{const day=today();if(!progress.days.includes(day)){progress.days.push(day);save();}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const contains=(list,word)=>list.includes(word);
const addUnique=(list,word)=>{if(!list.includes(word)){list.push(word);markDay();save();}};
const getDailyWord=()=>WORDS[Math.floor(Date.now()/86400000)%84];
const getStreak=()=>{const dates=new Set(progress.days);let date=new Date();let count=0;if(!dates.has(date.toLocaleDateString('en-CA')))date.setDate(date.getDate()-1);while(dates.has(date.toLocaleDateString('en-CA'))){count++;date.setDate(date.getDate()-1)}return count};
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function speak(text,slow=false){if(!('speechSynthesis'in window)){toast('当前浏览器不支持语音朗读，请使用新版 Chrome 或 Edge');return}speechSynthesis.cancel();const utter=new SpeechSynthesisUtterance(text);utter.lang='en-US';utter.rate=slow?.75:.9;utter.pitch=1.05;const voices=speechSynthesis.getVoices();utter.voice=voices.find(v=>v.lang==='en-US'&&/Google|Microsoft|Samantha/i.test(v.name))||voices.find(v=>v.lang.startsWith('en'))||null;speechSynthesis.speak(utter)}
function setPage(page){state.page=page;state.speechMessage='先听一遍发音，再点击「开始跟读」大声说出来吧！';document.querySelectorAll('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.page===page));$('#breadcrumbText').textContent=names[page];$('.sidebar').classList.remove('open');$('.overlay')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});render()}
function wordCard(word){const saved=contains(progress.saved,word.word);return `<article class="dict-card"><div class="dict-card-head"><div><h3>${esc(word.word)}</h3><div class="ipa">${esc(word.ipa)}</div></div><button class="tiny-btn ${saved?'saved':''}" data-action="save" data-word="${esc(word.word)}" aria-label="${saved?'取消收藏':'收藏'} ${esc(word.word)}">${saved?'♥':'♡'}</button></div><p>${esc(word.meaning)}</p><div class="dict-card-footer"><span>${esc(word.emoji)} ${esc(word.group)}</span><div class="card-controls"><button class="tiny-btn" data-action="speak" data-word="${esc(word.word)}" aria-label="朗读 ${esc(word.word)}">◖))</button><button class="tiny-btn" data-action="select" data-word="${esc(word.word)}" aria-label="查看 ${esc(word.word)}">↗</button></div></div></article>`}
function detailPanel(word,small=false){const saved=contains(progress.saved,word.word);return `<section class="panel word-panel"><div class="panel-top"><span class="mini-label">${small?'TODAY’S WORD · 今日单词':'WORD CARD · 单词卡片'}</span><span class="pill">${esc(word.emoji)} ${esc(word.group)}</span></div><div class="word-title"><h3>${esc(word.word)}</h3><button class="sound-button" data-action="speak" data-word="${esc(word.word)}" aria-label="朗读单词">◖))</button></div><div class="ipa">${esc(word.ipa)}</div><div class="meaning">${esc(word.meaning)}</div><div class="example"><em>${esc(word.sentence)}</em><small>${esc(word.translation)}</small></div><div class="panel-actions"><button class="ghost-btn" data-action="speak-example" data-word="${esc(word.word)}">🔊 听例句</button><button class="ghost-btn" data-action="save" data-word="${esc(word.word)}">${saved?'♥ 已收藏':'♡ 加入单词本'}</button><button class="ghost-btn" data-action="learn" data-word="${esc(word.word)}">${contains(progress.learned,word.word)?'✓ 已学会':'✓ 我学会了'}</button></div></section>`}
function home(){const daily=getDailyWord();const units=WORD_GROUPS.slice(0,8).map(g=>`<button class="unit-card" data-action="unit" data-group="${esc(g.name)}"><span class="unit-icon ${g.color}">${g.emoji}</span><strong>${esc(g.name)}</strong><small>${g.level} · ${g.rows.split('\n').length} 个单词 →</small></button>`).join('');return `<div class="welcome"><div><span class="eyebrow">HELLO, LITTLE EXPLORER!</span><h1>嗨，小小英语探险家！ 👋</h1><p>每天学一点，英语就会越来越棒。</p></div><span class="stars">✦ ✧ ✦</span></div><section class="hero"><div class="hero-copy"><span class="hero-tag">🌱 今日学习之旅</span><h2>让单词发芽，让表达开花！</h2><p>听一听、读一读、写一写，开启今天的英语冒险吧。</p><button class="primary-btn" data-action="start">开始探索 <span>→</span></button></div><div class="hero-art"><span class="spark one">✦</span><div class="mascot"><span class="face">•ᴗ•</span></div><span class="book-art">📖</span><span class="spark two">✧</span></div></section><div class="section-head"><h2>📊 我的学习足迹 <small>每一点进步都值得记录</small></h2></div><section class="stats-grid"><div class="stat-card"><span class="stat-emoji a">📚</span><div><strong>${progress.learned.length}</strong><small>已学会单词</small></div></div><div class="stat-card"><span class="stat-emoji b">🎤</span><div><strong>${progress.spoken.length}</strong><small>跟读通过</small></div></div><div class="stat-card"><span class="stat-emoji c">🔥</span><div><strong>${getStreak()}</strong><small>连续学习天数</small></div></div></section><div class="section-head"><h2>✨ 今天学什么</h2><button class="text-link" data-action="browse">查看全部单词 →</button></div><div class="learning-grid">${detailPanel(daily,true)}<section class="panel practice-panel"><div><span class="mini-label">SPEAK WITH ME</span><h3>大胆开口说英语 🎙️</h3><p>跟着读一读，让英语自然说出口。</p></div><div class="practice-graphic"><span>🎙️</span></div><button class="secondary-btn" data-action="go-speaking">去练习口语 →</button></section></div><div class="section-head"><h2>🧩 挑选喜欢的主题</h2><button class="text-link" data-action="browse">更多主题 →</button></div><div class="units-grid">${units}</div>`}
function filteredWords(){let words=state.page==='saved'?WORDS.filter(w=>contains(progress.saved,w.word)):WORDS;if(state.level!=='全部学段')words=words.filter(w=>w.level===state.level);if(state.group!=='全部主题')words=words.filter(w=>w.group===state.group);if(state.query.trim()){const q=state.query.toLowerCase().trim();words=words.filter(w=>w.word.includes(q)||w.meaning.includes(q)||w.group.includes(q))}return words}
function dictionary(saved=false){const words=filteredWords();const pageSize=12;const pages=Math.max(1,Math.ceil(words.length/pageSize));state.dictPage=Math.min(state.dictPage,pages);const shown=words.slice((state.dictPage-1)*pageSize,state.dictPage*pageSize);const chips=['全部主题',...WORD_GROUPS.filter(g=>state.level==='全部学段'||g.level===state.level).map(g=>g.name)].map(n=>`<button class="chip ${state.group===n?'active':''}" data-action="group" data-group="${esc(n)}">${esc(n)}</button>`).join('');let body=shown.map(wordCard).join('');if(!words.length)body=`<div class="empty-state" style="grid-column:1/-1"><span>🔎</span><strong>${saved?'单词本还是空的':'没有找到这个单词'}</strong><p>${saved?'点击单词卡片上的 ♡，把喜欢的词存进来。':'试试其他关键词，或者使用在线词典查询。'}</p>${!saved&&/^[a-z-]+$/i.test(state.query.trim())?'<button class="secondary-btn" data-action="online">在线查询这个单词 →</button>':''}</div>`;return `<div class="page-title"><span class="eyebrow">${saved?'MY WORD BOOK':'WORD DICTIONARY'}</span><h1>${saved?'我的单词本 ♡':'单词字典 📖'}</h1><p>${saved?'把喜欢的单词收集起来，随时温习。':'从熟悉的主题出发，慢慢认识更多英语单词。'}</p></div>${saved?'<div class="saved-intro">💚 你收藏的单词只保存在当前浏览器里。每天回来复习几个，就会记得越来越牢！</div>':''}<div class="toolbar"><div class="search-wrap"><span class="search-icon">⌕</span><input id="wordSearch" class="search-input" type="search" placeholder="搜索英语或中文，例如 apple / 苹果" value="${esc(state.query)}" autocomplete="off" /></div><select class="filter-select" id="levelSelect" aria-label="选择学段"><option ${state.level==='全部学段'?'selected':''}>全部学段</option><option ${state.level==='小学'?'selected':''}>小学</option><option ${state.level==='初中'?'selected':''}>初中</option></select></div><div class="category-chips">${chips}</div>${state.onlineWord?`<div style="margin-top:18px">${detailPanel(state.onlineWord)}</div>`:''}<div class="result-count">找到 ${words.length} 个单词 · 内置 ${WORDS.length} 个主题词汇</div><div class="dictionary-grid">${body}</div>${pages>1?`<div class="pagination"><button class="page-btn" data-action="page" data-page="${state.dictPage-1}" ${state.dictPage===1?'disabled':''}>上一页</button><button class="page-btn active">${state.dictPage} / ${pages}</button><button class="page-btn" data-action="page" data-page="${state.dictPage+1}" ${state.dictPage===pages?'disabled':''}>下一页</button></div>`:''}`}
function speaking(){const word=WORDS[state.practiceIndex%WORDS.length];return `<div class="page-title"><span class="eyebrow">SPEAKING PRACTICE</span><h1>口语跟读 🎙️</h1><p>先听，再跟着说。大胆开口，每次练习都是进步！</p></div><div class="training-layout"><section class="training-card"><span class="training-kicker">🔊 跟读挑战 · 第 ${state.practiceIndex+1} 个单词</span><h2 class="training-word">${esc(word.word)}</h2><div class="training-ipa">${esc(word.ipa)}</div><div class="training-meaning">${esc(word.meaning)}</div><div class="training-example">${esc(word.sentence)}<small>${esc(word.translation)}</small></div><div class="training-actions"><button class="ghost-btn" data-action="speak" data-word="${esc(word.word)}">🔊 听标准发音</button><button class="ghost-btn" data-action="slow" data-word="${esc(word.word)}">🐢 慢速听</button><button class="primary-btn" data-action="record">🎙️ 开始跟读</button></div><div class="speech-status" id="speechStatus" aria-live="polite">${esc(state.speechMessage)}</div><div class="training-footer"><button class="secondary-btn" data-action="next-speaking">换一个单词 →</button><button class="ghost-btn" data-action="speak-example" data-word="${esc(word.word)}">听例句</button></div></section><aside class="side-tip"><div class="tip-emoji">🗣️</div><h3>跟读小窍门</h3><ol><li>先听两遍标准发音。</li><li>放慢速度，大声读出来。</li><li>读完再听例句，试着跟读整句。</li></ol><p>跟读识别需要浏览器支持，并允许使用麦克风。识别结果是练习提示，不代表精确的发音评分。</p></aside></div>`}
function dictation(){const word=WORDS[state.spellingIndex%WORDS.length];const done=state.spellingIndex;return `<div class="page-title"><span class="eyebrow">SPELLING CHALLENGE</span><h1>单词默写 ✏️</h1><p>听发音、看中文，自己拼出正确的英文单词。</p></div><div class="training-layout"><section class="training-card"><span class="training-kicker">✏️ 默写闯关 · 第 ${done+1} 题</span><div class="progress-line"><div class="progress-fill" style="width:${Math.min(100,(done%10)*10)}%"></div></div><div class="progress-meta"><span>已完成 ${done} 题</span><span>每 10 题一轮</span></div><div class="dictation-prompt"><strong>${esc(word.meaning)}</strong><small>提示：${word.word.length} 个英文字母</small></div><button class="ghost-btn" data-action="speak" data-word="${esc(word.word)}">🔊 听单词发音</button><p style="font-size:12px;color:#9aa7ae;margin:20px 0 8px">把你听到的单词写在这里：</p><form id="spellingForm"><input class="answer-input" id="spellingAnswer" type="text" inputmode="text" autocapitalize="off" autocomplete="off" spellcheck="false" placeholder="在这里输入英文单词" aria-label="默写答案" ${state.spellingResult?'disabled':''}/><div class="training-footer"><button class="primary-btn" type="submit" ${state.spellingResult?'disabled':''}>检查答案 ✓</button><button class="ghost-btn" type="button" data-action="show-answer">查看答案</button><button class="secondary-btn" type="button" data-action="next-spelling">下一题 →</button></div></form>${state.spellingResult?`<div class="feedback ${state.spellingResult.correct?'good':'bad'}">${esc(state.spellingResult.message)}</div>`:''}</section><aside class="side-tip" style="background:#fff7e7"><div class="tip-emoji">📝</div><h3>记单词的小秘诀</h3><ol><li>先听发音，边读边想字母。</li><li>动手拼写，比只看一眼记得更牢。</li><li>拼错了也没关系，再试一次！</li></ol><p>答对的单词会记录在本机浏览器中。</p></aside></div>`}
function render(){if(state.page==='home')main.innerHTML=home();else if(state.page==='primary')main.innerHTML=primaryPage();else if(state.page==='dictionary')main.innerHTML=dictionary();else if(state.page==='saved')main.innerHTML=dictionary(true);else if(state.page==='speaking')main.innerHTML=speaking();else main.innerHTML=dictation()}
function selectWord(word){const found=WORDS.find(w=>w.word===word)||state.onlineWord;if(!found)return;state.selected=found;state.onlineWord=found;state.page='dictionary';document.querySelectorAll('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.page==='dictionary'));$('#breadcrumbText').textContent=names.dictionary;render();main.scrollIntoView({behavior:'smooth'})}
async function onlineLookup(){const q=state.query.trim().toLowerCase();if(!/^[a-z-]{2,30}$/.test(q))return;toast('正在查询在线词典…');try{const res=await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(q)}`);if(!res.ok)throw Error();const data=(await res.json())[0];const definition=data.meanings?.flatMap(m=>m.definitions||[]).find(x=>x.example)||data.meanings?.[0]?.definitions?.[0];state.onlineWord={word:data.word,ipa:data.phonetic||data.phonetics?.find(x=>x.text)?.text||'音标暂缺',meaning:'英文释义：'+(definition?.definition||'暂无释义'),sentence:definition?.example||`Let's learn the word ${data.word}.`,translation:'在线词典暂不提供中文例句',group:'在线词典',emoji:'🌐',level:'扩展词汇'};render();toast('在线词典已找到这个单词')}catch{toast('在线查询暂时不可用，请检查网络后重试')}}
function startRecording(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){state.speechMessage='当前浏览器不支持语音识别。可以先使用朗读按钮跟读，推荐在 Chrome 或 Edge 中开启麦克风练习。';render();return}const word=WORDS[state.practiceIndex%WORDS.length];const recognition=new SpeechRecognition();recognition.lang='en-US';recognition.interimResults=false;recognition.maxAlternatives=3;state.speechMessage='🎙️ 正在听你说，请读出 '+word.word+'…';render();recognition.onresult=e=>{const guesses=Array.from(e.results[0]).map(x=>x.transcript.trim().toLowerCase().replace(/[.!?]/g,''));const matched=guesses.some(x=>x===word.word||x.split(/\s+/).includes(word.word));if(matched){addUnique(progress.spoken,word.word);state.speechMessage=`🌟 真棒！我听到了「${guesses[0]}」。试着再读一读完整例句吧！`}else state.speechMessage=`我听到的是「${guesses[0]}」。再听一遍发音，慢慢试一次吧！`;render()};recognition.onerror=e=>{state.speechMessage=e.error==='not-allowed'?'请允许浏览器使用麦克风后再试。':'暂时没有听清，请靠近麦克风再试一次。';render()};recognition.onnomatch=()=>{state.speechMessage='还没有听清，试着放慢一点再读。';render()};try{recognition.start()}catch{state.speechMessage='麦克风暂时无法启动，请刷新页面后重试。';render()}}
document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item[data-page]');if(nav){setPage(nav.dataset.page);return}const btn=e.target.closest('[data-action]');if(!btn)return;const action=btn.dataset.action;const word=btn.dataset.word;const entry=WORDS.find(w=>w.word===word)||state.onlineWord;if(action==='speak')speak(word);else if(action==='slow')speak(word,true);else if(action==='speak-example'&&entry)speak(entry.sentence);else if(action==='save'){const i=progress.saved.indexOf(word);if(i>=0){progress.saved.splice(i,1);toast('已从单词本移除')}else{addUnique(progress.saved,word);toast('已加入我的单词本 ♡')}save();render()}else if(action==='learn'){addUnique(progress.learned,word);toast('记住啦！继续加油 🌱');render()}else if(action==='select')selectWord(word);else if(action==='start'||action==='browse')setPage('dictionary');else if(action==='go-speaking')setPage('speaking');else if(action==='unit'){state.group=btn.dataset.group;state.level='全部学段';state.query='';state.dictPage=1;setPage('dictionary')}else if(action==='group'){state.group=btn.dataset.group;state.dictPage=1;state.onlineWord=null;render()}else if(action==='page'){state.dictPage=Number(btn.dataset.page);render();window.scrollTo({top:0,behavior:'smooth'})}else if(action==='online')onlineLookup();else if(action==='record')startRecording();else if(action==='next-speaking'){state.practiceIndex=(state.practiceIndex+1)%WORDS.length;state.speechMessage='先听一遍发音，再点击「开始跟读」大声说出来吧！';render()}else if(action==='next-spelling'){state.spellingIndex=(state.spellingIndex+1)%WORDS.length;state.spellingResult=null;render();$('#spellingAnswer')?.focus()}else if(action==='show-answer'){const answer=WORDS[state.spellingIndex%WORDS.length].word;state.spellingResult={correct:false,message:`答案是 ${answer}。听一遍发音，再大声读出来吧！`};render()}});
document.addEventListener('input',e=>{if(e.target.id==='wordSearch'){const pos=e.target.selectionStart;state.query=e.target.value;state.dictPage=1;state.onlineWord=null;render();const input=$('#wordSearch');input.focus();input.setSelectionRange(pos,pos)}});
document.addEventListener('change',e=>{if(e.target.id==='levelSelect'){state.level=e.target.value;state.group='全部主题';state.dictPage=1;render()}});
document.addEventListener('submit',e=>{if(e.target.id!=='spellingForm')return;e.preventDefault();if(state.spellingResult)return;const answer=$('#spellingAnswer').value.trim().toLowerCase();const word=WORDS[state.spellingIndex%WORDS.length].word;if(!answer){toast('先写下你的答案吧');return}const correct=answer===word;if(correct){addUnique(progress.spelled,word);addUnique(progress.learned,word)}state.spellingResult={correct,message:correct?`答对啦！${word} = ${WORDS[state.spellingIndex%WORDS.length].meaning} 🎉`:`再加油！正确拼写是 ${word}。`};render()});
$('#menuButton').addEventListener('click',()=>{$('.sidebar').classList.toggle('open');let overlay=$('.overlay');if(!overlay){overlay=document.createElement('div');overlay.className='overlay';document.body.appendChild(overlay);overlay.addEventListener('click',()=>{$('.sidebar').classList.remove('open');overlay.classList.remove('open')})}overlay.classList.toggle('open')});
$('#todayDate').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
const startPage=new URLSearchParams(location.search).get('page');
if(startPage&&Object.prototype.hasOwnProperty.call(names,startPage))setPage(startPage);else render();
